from typing import Dict

CARD_IMAGES: Dict[str, str] = {
"Рыцарь": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/01_rytsar.jpg",
"Вызов": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/02_vyzvanie.jpg",
"Сорока": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/03_soroka.jpg",
"Чайка": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/04_chayka.jpg",
"Дом": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/05_dom.jpg",
"Букет": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/06_buket.jpg",
"Квартира": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/07_kvartira.jpg",
"Лук": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/08_luk.jpg",
"Рюмка": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/09_ryumka.jpg",
"Меч": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/10_mech.jpg",
"Крест": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/11_krest.jpg",
"Кольцо": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/12_koltso.jpg",
"Ребенок": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/13_rebenok.jpg",
"Корабль": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/14_korabl.jpg",
"Козырь": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/15_kozyr.jpg",
"Дорога": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/16_doroga.jpg",
"Письма": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/17_pisma.jpg",
"Деньги": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/18_dengi.jpg",
"Звоны": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/19_zvony.jpg",
"Сердце": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/20_serdce.jpg",
"Дар": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/21_dar.jpg",
"Путешествие": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/22_puteshestvie.jpg",
"Мыслитель": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/23_myslitel.jpg",
"Голова": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/24_golova.jpg",
"Книга": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/26_kniga.jpg",
"Береза": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/28_bereza.jpg",
"Лиса": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/27_puteshestvie.jpg",
"Лотос": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/30_lotos.jpg",
"Солнце": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/31_solntse.jpg",
"Луна": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/32_luna.jpg",
"Ключ": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/33_klyuch.jpg",
"Корона": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/35_korona.jpg",
"Крысы": "https://raw.githubusercontent.com/viten1/LenormanBot/main/cards/29_krysy.jpg",
}